language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0

# Downgrade rubygems because rails 2.3 does not work on 2.0+
before_install:
  - gem update --system 1.8.25

env:
  - RAILS_VERSION=2.x
  - RAILS_VERSION=3.0.20
  - RAILS_VERSION=3.1.12
  - RAILS_VERSION=3.2.3
  - RAILS_VERSION=3.2.13
  - RAILS_VERSION=3.2.12 DB_CHARMER_GEM=1.8.3

notifications:
  recipients:
    - alexey@kovyrin.net

script: ./ci_build

# Whitelist branches to test
branches:
  only:
    - master
    - multithreading

# Build matrix configuration
matrix:
  exclude:
    # Do not run Rails 2.x tests on ruby 1.9
    - rvm: 1.9.3
      env: RAILS_VERSION=2.x

    # Do not run Rails 2.x tests on ruby 2.0
    - rvm: 2.0.0
      env: RAILS_VERSION=2.x

    # Do not run Rails 3.0 tests on ruby 2.0
    - rvm: 2.0.0
      env: RAILS_VERSION=3.0.20

    # Do not run Rails 3.1 tests on ruby 2.0
    - rvm: 2.0.0
      env: RAILS_VERSION=3.1.12

    # Do not run early Rails 3.2 tests on ruby 2.0
    - rvm: 2.0.0
      env: RAILS_VERSION=3.2.3
